version: '3.4'

services:
  testimg:
    image: testimg
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ${PWD}/testdata.json:/app/testdata.json
